pipeline {
  agent any
  stages {
    stage('Log Ant version info') {
      steps {
        sh 'ant -version'
      }
    }
    stage('Ant Build') {
      steps {
        git 'https://gitlab.training.dagility.com/manojkumar_gnanasekaran/dagilitytrainingantfreestyle.git'
        sh 'ant -f build.xml'
      }
    }
  }
}
